### ISSUE TITLE
Récupérer les "clés" de toutes les formations de MIDO

### ISSUE THREAD

**Issue by TajouriSarra** [marcellinodour/MIDO-SVG#11]
Bonjour Monsieur, 

On n’a pu récupérer que les cours du M1 MIAGE App étant donné qu'on dispose du programID (plaquette-MIDO) mais nous n’avons pas les « clés » pr les autres formations. 
Pouvez vous nous aider svp?

**Comment by oliviercailloux** [comment]
Regardez dans les tests unitaires de plaquette-mido le moyen de chercher les formations par d’autres critères que la clé.
