### ISSUE TITLE
Restaurer la compilation

### ISSUE THREAD

**Issue by oliviercailloux** [marcellinodour/MIDO-SVG#16]
Voudriez-vous restaurer la compilation du projet ? Depuis (au moins) l’ajout de la classe DataRecuperator, le projet ne compile plus.

Ceci est à traiter en priorité.

**Comment by marcellinodour** [comment]
Le GitHub Action ne s’exécute pas correctement de par le fait que le fichier WSDL_ACCESS ne soit pas accessible (et heureusement !). Nous avons donc créer une variable environnement secret du nom WSDL_ACCESS. Avec une modification dans le fichier .yml récupérant cette variable et une modification dans le POM. Cependant rien n’y fait, l’authentification WSDL attend un fichier et non une variable. J’ai essayé de chercher sur internet s’il était possible par le moyen d’une balise (<username> et <password> par exemple ; auquel cas la solution serait toute trouvée) mais cela ne semble pas exister … Est-il possible de créer un fichier secret sur GitHub ? pareillement, je n’ai absolument rien trouvé sur ce point.

**Comment by oliviercailloux** [comment]
Je pense important de garder les discussions séparées et focalisées pour éviter les malentendus. Cette issue est à propos du problème de compilation. Votre commentaire parle du fait que le projet ne s’exécute pas sur le serveur distant à cause du fichier manquant, ce qui est un autre problème. 

Voudriez-vous créer une autre issue spécifiquement concernant le GH Action, de façon à garder cette conversation-ci concentrée sur le problème de compilation ?

**Comment by marcellinodour** [comment]
Oui toutes nos excuses.
Cependant nous pensions que le problème est lié dans le sens où le projet ne se compile pas de par le fait que ce dernier n’exécute pas correctement la dépendance wsimport du pom.xml.

Nous somme sommes donc un peu perdu. Nous comprenons que le projet ne se compile pas sur master a l’heure actuelle (principalement dû aussi aux classe ObjectTransformer et DataRecuperator) problème - semble-t-il - pallié après validation de la PR #18. (Car tout se compile comme il faut sur la branch dev-BDD)

Nous ouvrons bien une autre Issue pour le problème d’accès WSDL.

**Comment by oliviercailloux** [comment]
Vous avez raison quand au fait que le projet ne peut pas compiler sur un serveur externe tant que le problème d’accès WSDL existe. Mais dans cette issue je fais référence au fait qu’il ne compile pas également chez moi, en local, et avec accès WSDL bien configuré.

Si un changement dans la PR 18 résout le problème, tant mieux. Je vous invite à introduire une PR séparée qui résout le problème de compilation, car je pourrai l’accepter sans attendre, alors que je ne souhaite pas accepter d’autres changements (tels que ceux introduits par la PR 18 non liés aux issues soulevées ici) tant que les actions GitHub ne passent pas.
