### ISSUE TITLE
GH Action et fichier WSDL

### ISSUE THREAD

**Issue by brulej** [marcellinodour/MIDO-SVG#19]
Avant l'introduction du workflow github, nous utilisions le fichier WSDL_access.txt pour accéder et récupérer la structure de la base de données lors de la compilation maven. (Via la balise <xauthfiles>)
En utilisant un "secret" de github stockant le mot de passe, nous pouvons accéder à la BDD.  Cependant, cela ne fonctionne pas pour l'authentification WSDL car c'est un fichier qui est attendu.

Comment pouvons-nous faire pour résoudre ce problème ? Dans la partie "Limits for secrets" de la documentation officielle (https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) ils parlent d'encoder un fichier. Est-ce la solution attendue ?

**Comment by oliviercailloux** [comment]
Comme j’indiquais par e-mail : voyez SVP la doc de plaquette-mido (qui fonctionne avec Travis et pas GitHub Workflow, mais le principe est le même, vous devriez vous y retrouver). Dites-moi si vous restez bloqués.

**Comment by marcellinodour** [comment]
Je passe issue à Résolu, car tout fonctionne à merveille sur la branche EVOL_For_COMPIL (cf PR #20 )
